---
- name: Create Vault directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0750
  loop:
    - "{{ vault_config_dir }}"
    - "{{ vault_data_dir }}"
    - "{{ vault_log_dir }}"

- name: Install dependencies
  apt:
    name:
      - curl
      - gnupg
      - software-properties-common
    state: present

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_codename }} main"
    state: present
    filename: hashicorp

- name: Install Vault
  apt:
    name: vault={{ vault_version }}
    state: present
    update_cache: yes

- name: Create Vault system user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: /bin/false
    home: /nonexistent

- name: Load PostgreSQL credentials
  include_vars:
    file: /etc/vault.d/db_credentials
    name: db_creds

- name: Configure Vault
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_dir }}/vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0640
  notify: restart vault

- name: Configure systemd service
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart vault

- name: Enable and start Vault service
  service:
    name: vault
    state: started
    enabled: yes