---
- name: Update apt package index
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common dependencies
  apt:
    name:
      - curl
      - gnupg
      - software-properties-common
      - python3-pip
      - unzip
      - jq
    state: present