---
- name: Deploy HashiCorp Vault with PostgreSQL backend
  hosts: vault_servers
  become: yes
  vars:
    vault_version: "1.16.0"
    # Override any other defaults as needed
    vault_auto_init: true    # Set to true to initialize Vault
    vault_auto_unseal: true  # Set to true to unseal Vault
  roles:
    - vault-role