---
- name: Setup common dependencies
  hosts: all
  become: yes
  roles:
    - common

- name: Setup PostgreSQL for Vault
  hosts: vault_db
  become: yes
  roles:
    - postgresql

- name: Setup HashiCorp Vault
  hosts: vault_server
  become: yes
  roles:
    - vault