---
# SonarQube version
sonarqube_version: "9.9.1.69595"
sonarqube_download_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
sonarqube_download_validate_certs: yes

# Installation directory
sonarqube_install_dir: /opt/sonarqube
sonarqube_user: sonar
sonarqube_group: sonar

# Java version to install
java_package: openjdk-17-jdk

# Database configuration
sonarqube_db_host: localhost
sonarqube_db_port: 5432
sonarqube_db_name: sonar
sonarqube_db_user: sonar
sonarqube_db_password: sonarpassword

# Web configuration
sonarqube_web_host: 0.0.0.0
sonarqube_web_port: 9000
sonarqube_web_context: /

# Elasticsearch settings
sonarqube_search_java_opts: "-Xmx512m -Xms512m -XX:MaxDirectMemorySize=256m -XX:+HeapDumpOnOutOfMemoryError"

# System limits - required for Elasticsearch
sonarqube_fs_vm_max_map_count: 262144
sonarqube_fs_file_max: 65536
sonarqube_nofile_soft_limit: 65536
sonarqube_nofile_hard_limit: 65536