---
- name: restart postgresql
  systemd:
    name: "postgresql@{{ postgresql_version }}-main"
    state: restarted
  listen: "restart postgresql"

- name: reload postgresql
  systemd:
    name: "postgresql@{{ postgresql_version }}-main"
    state: reloaded
  listen: "reload postgresql"
