---
- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: postgresql

- name: Import PostgreSQL GPG key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install PostgreSQL
  apt:
    name:
      - postgresql-{{ postgresql_version }}
      - postgresql-client-{{ postgresql_version }}
      - postgresql-contrib-{{ postgresql_version }}
      - postgresql-server-dev-{{ postgresql_version }}
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is running and enabled
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create Vault database user
  become_user: postgres
  postgresql_user:
    name: "{{ vault_db_user }}"
    password: "{{ vault_db_password }}"
    role_attr_flags: "CREATEDB,CREATEROLE,LOGIN"
    state: present

- name: Create Vault database
  become_user: postgres
  postgresql_db:
    name: "{{ vault_db_name }}"
    owner: "{{ vault_db_user }}"
    state: present

- name: Configure PostgreSQL to allow Vault connections
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0640
  notify: restart postgresql

- name: Configure PostgreSQL to listen on all interfaces
  lineinfile:
    path: "{{ postgresql_conf_dir }}/postgresql.conf"
    regexp: "^listen_addresses"
    line: "listen_addresses = '*'"
    state: present
  notify: restart postgresql