---
- name: Install and configure MongoDB
  hosts: localhost
  become: yes
  roles:
    - mongodb
  vars:
    mongodb_databases:
      - name: "erp-crm"
        users:
          - username: "dev-user"
            password: "Erp-Crm$#890QWE"
            roles: "readWrite"
      - name: "test-db"
        users:
          - username: "test-user"
            password: "TestPass123"
            roles: "readWrite"