postgresql_version: "14"
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"


# SonarQube database settings
sonarqube_db_name: sonar
sonarqube_db_user: sonar
sonarqube_db_password: sonarpassword