---
- name: restart vault
  systemd:
    name: vault
    state: restarted
    daemon_reload: yes
  listen: "restart vault"

- name: reload vault
  systemd:
    name: vault
    state: reloaded
  listen: "reload vault"